title: "プロダクトデザインの旅路から学んだデザインのメモ"
summary: "日々の発見や直面する困難について、常にメモを取ってきました。これらを整理して、私の思考と感情の記録を集めたものです。単なる記述です。"
topics: ["frontend", "プロダクトデザイン", "uiuxdesign"]
published: false
price: 0 # 有料の場合200〜5000
chapters:
  - a6adomqn
  - bynazjd7s
  - cmjli9r30
  - dupxqoimp
  - e9wxch7am
  - e9xxch7am
  - f0ui2olwj
  - gxgirpg0g
  - h9sr7sodo
  - ijtf6u9qr
  - jngqyqay1
  - kod73fg12
  - l7q0ilygt
  - n8vsva8xg
