title: "Figma によるデザインシステム入門"
summary: "本書は Figma によるデザインシステムコースの日本語訳になります。デザインシステムに興味がある人や構築しようとしている人もチェックしてみてください。デザインシステムに縁のないデザイナーや開発者のためにプロダクトと向き合った最適なデザインシステムを探求するための材料になれば嬉しく思います。"
topics: ["figma", "frontend", "デザインシステム", "uiuxdesign"]
published: true
price: 0
chapters:
  - chapter1 # チャプター1
  - chapter2 # チャプター2
  - chapter3 # チャプター3
  - chapter4 # チャプター4
  - chapter5 # チャプター5
  - chapter6 # チャプター6
  - chapter7 # チャプター7
  - chapter8 # チャプター8
  - chapter9 # チャプター9
  - chapter10 # チャプター9
  - chapter11 # チャプター11
  - chapter12 # チャプター12
  - chapter13 # チャプター13
  - chapter14 # チャプター14
  - chapter15 # チャプター15
  - chapter16 # チャプター16
  - chapter17 # チャプター17
  - chapter18 # チャプター18
  - chapter19 # チャプター19
  - chapter20 # チャプター20
  - chapter21 # チャプター21
  - chapter22 # チャプター22
  - chapter23 # チャプター23
  - chapter24 # チャプター24
  - chapter25 # チャプター25
  - chapter26 # チャプター26
