title: "デザインシステムを支えるアクセシビリティのドキュメント作成術"
summary: ""
topics: ["figma", "frontend", "デザインシステム", "ui", "accessibility"]
published: false
price: 0
chapters:
  - all
  - 7d48G8qz # ユーザーを理解する: アクセシビリティの本質
  - GGd0xvxb # コンポーネントにアクセシビリティを実装 : デザインシステムのアクセシビリティ